string[] sqls =
{
    "select * from tbl where a = 123",
    "SELECT * FROM table_name;",
    "SELECT CustomerName, City FROM Customers;",
    "SELECT DISTINCT Country FROM Customers;",
    "SELECT COUNT(DISTINCT Country) FROM Customers;",
    "SELECT Count(*) AS DistinctCountries FROM (SELECT DISTINCT Country FROM Customers);",
    "SELECT * FROM Customers WHERE Country='Mexico';",
    "SELECT * FROM Customers\r\nWHERE CustomerID=1;",
    "SELECT * FROM Customers WHERE Country='Germany' AND City='Berlin';",
    "SELECT * FROM Customers WHERE City='Berlin' OR City='München';",
    "SELECT * FROM Customers\r\nORDER BY Country;",
    "SELECT * FROM Customers\r\nORDER BY Country DESC;",
    "SELECT * FROM Customers ORDER BY Country, CustomerName;",
    "SELECT * FROM EMPLOYEE_TBL;",
    "SELECT EMP_ID FROM EMPLOYEE_TBL;",
    "SELECT EMP_ID FROM EMPLOYEE_TBL;",
    "SELECT EMP_ID, LAST_NAME FROM EMPLOYEE_TBL;",
    "SELECT EMP_ID, LAST_NAME FROM EMPLOYEE_TBL WHERE EMP_ID = '333333333';",
    "SELECT EMP_ID, LAST_NAME FROM EMPLOYEE_TBL WHERE CITY = 'INDIANAPOLIS' ORDER BY EMP_ID;",
    "SELECT EMP_ID, LAST_NAME FROM EMPLOYEE_TBL WHERE CITY = 'INDIANAPOLIS' ORDER BY EMP_ID, LAST_NAME DESC;",
    "SELECT EMP_ID, LAST_NAME FROM EMPLOYEE_TBL WHERE CITY = 'INDIANAPOLIS' ORDER BY 1;",
    "SELECT EMP_ID, LAST_NAME FROM EMPLOYEE_TBL WHERE CITY = 'INDIANAPOLIS' ORDER BY 2, 1;",
    "SELECT COUNT(*) FROM TABLE_NAME;",
    "SELECT COUNT(*) FROM PRODUCTS_TBL; ",
    "SELECT COUNT(PROD_ID) FROM PRODUCTS_TBL;",
    "SELECT EMP_ID FROM SCHEMA.EMPLOYEE_TBL;",
    "SELECT COLUMN_NAME ALIAS_NAME FROM TABLE_NAME;",
    "select prod_desc,     prod_desc product from products_tbl;",
};
